printf("\nRecusive Display: ");
    // RDisplay(first);
    // printf("\nReverse Display: ");
    // ReverseDisplay(first);
    // printf("\nIterative : Number of Node is = %d ",Count(first));
    // printf("\nRecursive : Number of Node is = %d ",RCount(first));
    // printf("\nIterative : Sum of all element = %d ",Sum(first));
    // printf("\nAverage of all element = %f ",Avg(first));
    // printf("\nRecursive : Sum of all elements = %d ",RSum(first));
    // printf("\nIterative : Max of all elements = %d ",Max(first));
    // printf("\nRecursive : Max of all elements = %d ",RMax(first));
    // printf("\nIterative : Min of all elements = %d ",Min(first));
    // printf("\nRecursive : Min of all elements = %d ",RMin(first));
    // printf("\nIterative : Linear Search = %d ",LSearch(first,15));
    // temp = LSearch(first,15); // address always stored in pointer.
    // temp !=NULL ? printf("\nAddress = %d and key = %d",temp,temp->data):printf("address = %d and data = %d",temp,temp->data); // Verification line for the output
    // printf("\nRecursive : Linear Search = %d ",RLSearch(first,15));
    // printf("\nImproved Linear Search = %d ",MoveToHeadSearch(first,55));
    // printf("\nDisplay: ");
    // Display(first);
    // Insert(first,8,55);
    // printf("\nDisplay: ");
    // Display(first);
    // printf("\nDisplay: before SortedInsert: ");
    // SortedInsert(first,10);
    // SortedInsert(first,12);
    // SortedInsert(first,13);
    // SortedInsert(first,13);
    // SortedInsert(first,13);
    // SortedInsert(first,60);
    // Display(first);
    // printf("\nDeleted = %d ",Delete(first,8));
    // printf("\nDisplay:After Deletion ");
    // Display(first);
    // printf("\nIs Linked List Sorted = %d",isSorted(first));
    // printf("\nRemoved Duplicate: ");
    // RemoveDuplicate(first);
    // Display(first);